version: '3.8'

services:
  web:
    image: flask-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FLASK_APP_PORT}:5000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    # depends_on:
      # - redis

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "${REDIS_PORT}:6379"
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #   command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

networks:
  default:
    driver: overlay